### ISSUE TITLE
DBM-SpellTimers Not Work

### ISSUE THREAD

**Issue by swetlover** [DeadlyBossMods/DBM-SpellTimers#1]
**Describe the bug**
DBM-SpellTimers Not Work.
I have removed the retail spell ID and added the Classic spell ID, but it does not work.
**Do you have an error log of what happened?**
none
**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**
X-Min-Interface: 80000
**Was it working in a previous version? If yes, which was the last good one?**
Dont know！
**Additional context**
Classic version , Chinese client.

**Comment by MysticalOS** [comment]
It's not going to work in classic, because classic doesn't have spellIDs only spell names. This plugin hasn't been made classic compatible

**Comment by swetlover** [comment]
Oh,thanks for your replay!
This page said is support Classic.
https://www.curseforge.com/wow/addons/deadly-boss-mods
SpellTimers (Classic & Retail)

**Comment by QartemisT** [comment]
Resolved as of https://github.com/DeadlyBossMods/DBM-SpellTimers/commit/4721f605716e5cbf33bc7ebefacbdfef1fa90619
