### ISSUE TITLE
DBM alerts that this is out of date

### ISSUE THREAD

**Issue by nahuelg90** [DeadlyBossMods/DBM-SpellTimers#4]
With the new DBM Version now I get a constant Warning message that says that DBM-SpellTimers must be updated or deleted. But this is the latest version

**Comment by Desdemonique** [comment]
I am receiving the same error repeatedly in-game: "<DBM> WARNING: An old version of DBM-SpellTimers is present that breaks DBM.  DBM-SpellTimers must be updated or removed for DBM to function properly. Update will require a game restart.
