### ISSUE TITLE
No spell timers appear

### ISSUE THREAD

**Issue by mmolad** [DeadlyBossMods/DBM-SpellTimers#7]
I've checked and rechecked my settings and no spell timers are appearing.  What steps can I take to debug/troubleshoot?  DBM timers are appearing otherwise.

**Comment by QartemisT** [comment]
If you are inside of an arena/battleground, you need to have the "Show cooldowns also in battlegrounds and arenas" turned on.
If you are outside of a raid, you need to have "Show cooldowns only from group members" turned off.

Besides this, I am unable to replicate this issue. If this is still a problem, please re-open the ticket and I can assist you further.

**Comment by mmolad** [comment]
Sadly this issue still persists.  What is interesting is that Rebirth is tracked, but nothing else.

**Comment by QartemisT** [comment]
Can you send me the DBM-SpellTimers.lua from inside your WTF folder, so I can see if its replicatable with your exact settings :)

**Comment by mmolad** [comment]
> Can you send me the DBM-SpellTimers.lua from inside your WTF folder, so I can see if its replicatable with your exact settings :)

https://gist.github.com/mmolad/b3538c4f76255e9342396290e982ec30

Looking at it now, it seems like only Rebirth and 1 other spell are explicitly enabled, despite the UI showing them all checked.

**Comment by QartemisT** [comment]
I see the issue right away :D

The checkbox on the side of the spell is the enable feature :P Only rebirth is flagged as enabled.

**Comment by QartemisT** [comment]
I do however see issue within code that would make it appear elsewise. This is fixed in a new release that's going out now :)

**Comment by mmolad** [comment]
This appears active again. @QartemisT
