### ISSUE TITLE
Icons on Spells

### ISSUE THREAD

**Issue by orionshock** [DeadlyBossMods/DBM-SpellTimers#8]
**Describe the bug**
Classic Version - there are no icons on the bars.

![image](https://user-images.githubusercontent.com/160723/107600851-302d7b00-6be2-11eb-91f8-1351ccba3bd1.png)

**Comment by QartemisT** [comment]
Have you turned icons off inside of DBM-Core? This can be found inside of "/dbm -> options -> timers -> bar apperance"

**Comment by orionshock** [comment]
> Have you turned icons off inside of DBM-Core? This can be found inside of "/dbm -> options -> timers -> bar apperance"

Icons Enabled there. All the normal stuff from the boss mods have icons and show as expected.
I do have icons set to show on the right side -- tho when i too that screenshot it was set left

**Comment by orionshock** [comment]
after further research, I appear to be asking the impossible : 

>  Patch 1.13.2 (2019-08-26): The spellId and extraSpellId parameters are defunct in Classic, returning 0 to resemble the pre-2.4.0 combat log.
https://wow.gamepedia.com/COMBAT_LOG_EVENT

**Comment by MysticalOS** [comment]
That's a big in classic. has always been there. it's because the way the code works when you input a spellId it translates to name right away, and as a result spellicon look up fials because it's being looked up with name instead of ID as expected. I saw that bug months ago just forgot about it :D

**Comment by orionshock** [comment]
however the spell id is available, as it's required when setting your own spells to watch. 

Line 371 & 387:
> SpellBarIndex[bartext] = Bars:CreateBar(v.cooldown, bartext, GetSpellTexture(**v.spell**), nil, true)

makes it work as desired - tho i don't know how you'd code that to be retail & classic friendly
