### ISSUE TITLE
Doesnt load any spells other than repair bot or jeeves 

### ISSUE THREAD

**Issue by Phatpally** [DeadlyBossMods/DBM-SpellTimers#9]
![wow](https://user-images.githubusercontent.com/81857843/113476587-65b84d00-944a-11eb-8328-604eb8ad6be0.jpg)

**Describe the bug**

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
That's all that's built into mod by default. you have to add your own after that. Or are you saying you had your own but somehow lost them? It looks like you had a config reset

**Comment by Phatpally** [comment]
It use to work fine never hd to add anything Sent from my Galaxy
-------- Original message --------From: Adam ***@***.***> Date: 4/3/21  9:28 AM  (GMT-05:00) To: DeadlyBossMods/DBM-SpellTimers ***@***.***> Cc: Phatpally ***@***.***>, Author ***@***.***> Subject: Re: [DeadlyBossMods/DBM-SpellTimers] Doesnt load any spells other than repair bot or jeeves  (#9) 
That's all that's built into mod by default. you have to add your own after that. Or are you saying you had your own but somehow lost them? It looks like you had a config reset

**Comment by MysticalOS** [comment]
What likely happened is a long time ago spelltimers had more built in timers for a few things like shield wall etc, defensive CDs and you installed it back then so you had the old defaults. even when you upgraded spelltimers to new versions it didn't wipe old settings so you had more spells. something recently nuked your settings file (maybe a reinstall? new PC? etc) and you have the new defaults now, which only include those items. You'll have to readd anything missing that you want.

**Comment by Phatpally** [comment]
Ok so where do i find everything at? Spell id ectSent from my Galaxy
-------- Original message --------From: Adam ***@***.***> Date: 4/3/21  10:04 AM  (GMT-05:00) To: DeadlyBossMods/DBM-SpellTimers ***@***.***> Cc: Phatpally ***@***.***>, Author ***@***.***> Subject: Re: [DeadlyBossMods/DBM-SpellTimers] Doesnt load any spells other than repair bot or jeeves  (#9) 
What likely happened is a long time ago spelltimers had more built in timers for a few things like shield wall etc, defensive CDs and you installed it back then so you had the old defaults. even when you upgraded spelltimers to new versions it didn't wipe old settings so you had more spells. something recently nuked your settings file (maybe a reinstall? new PC? etc) and you have the new defaults now, which only include those items. You'll have to readd anything missing that you want.

**Comment by MysticalOS** [comment]
add spellIds for any player spell in UI you posted, just get spellids from wowhead and such.

**Comment by danadlyla** [comment]
Can confirm, even adding a SpellID and checking the box... BugGrabber / BugSack gave me this error when trying to use Disrupt on my Demon Hunter:

5x DBM-SpellTimers\SpellTimers.lua:390: attempt to index upvalue 'Bars' (a nil value)
[string "@DBM-SpellTimers\SpellTimers.lua"]:390: in function <DBM-SpellTimers\SpellTimers.lua:351>

Locals:
self = DBM_SpellTimers {
 0 = <userdata>
}
event = "COMBAT_LOG_EVENT_UNFILTERED"
addon = nil
_ = 1625352713.610000
combatEvent = "SPELL_CAST_SUCCESS"
_ = false
_ = "Player-3675-0A3767A2"
sourceName = "Shanini"
_ = 1297
_ = 0
_ = "Creature-0-4214-1116-700-79253-0000DF9F47"
destName = "Botani Grower"
_ = 68168
_ = 0
spellid = 183752
spellinfo = "Disrupt"
_ = false
instanceType = "none"
guikey = 5
v = <table> {
 enabled = true
 spell = 183752
 cooldown = 15
 bartext = "Disrupt: %player"
}
bartext = "Disrupt: Shanini"
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Disrupt: Shanini"
(*temporary) = 0
(*temporary) = nil
(*temporary) = "boss5"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'Bars' (a nil value)"
settings = <table> {
 enabled = true
 active_in_pvp = true
 showlocal = true
 disable_encounter = false
 only_from_raid = true
 own_bargroup = false
 portal_alliance = <table> {
 }
 spells = <table> {
 }
 show_portal = true
 portal_horde = <table> {
 }
}
addDefaultOptions = <function> defined @DBM-SpellTimers\SpellTimers.lua:140
default_settings = <table> {
 enabled = true
 active_in_pvp = true
 showlocal = true
 disable_encounter = true
 only_from_raid = true
 own_bargroup = false
 portal_alliance = <table> {
 }
 portal_horde = <table> {
 }
 show_portal = true
 spells = <table> {
 }
}
myportals = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
}
UnitFactionGroup = <function> defined =[C]:-1
rebuildSpellIDIndex = <function> defined @DBM-SpellTimers\SpellTimers.lua:125
eventsUnregistered = false
clearAllSpellBars = <function> defined @DBM-SpellTimers\SpellTimers.lua:333
CombatLogGetCurrentEventInfo = <function> defined =[C]:-1
spellEvents = <table> {
 SPELL_CAST_SUCCESS = true
 SPELL_HEAL = true
 SPELL_AURA_APPLIED = true
 SPELL_AURA_REFRESH = true
 SPELL_RESURRECT = true
}
IsInInstance = <function> defined =[C]:-1
DBM = <table> {
 CHAT_MSG_ADDON_LOGGED = <function> defined @DBM-Core\DBM-Core.lua:5078
 CopyAllModOption = <function> defined @DBM-Core\DBM-Core.lua:3705
 FindScenarioIDs = <function> defined @DBM-Core\DBM-Core.lua:7390
 PLAY_MOVIE = <function> defined @DBM-Core\DBM-Core.lua:7436
 FindDungeonMapIDs = <function> defined @DBM-Core\DBM-Core.lua:7362
 GetUnitIdFromGUID = <function> defined @DBM-Core\DBM-Core.lua:3396
 CopyProfile = <function> defined @DBM-Core\DBM-Core.lua:2031
 CHAT_MSG_MONSTER_EMOTE = <function> defined @DBM-Core\DBM-Core.lua:5669
 shortTermEventsRegistered = 1
 CHAT_MSG_WHISPER = <function> defined @DBM-Core\DBM-Core.lua:7100
 SendPVPTimers = <function> defined @DBM-Core\DBM-Core.lua:6911
 DeleteProfile = <function> defined @DBM-Core\DBM-Core.lua:2048
 DungeonMusic = <table> {
 }
 ShowUpdateReminder = <function> defined @DBM-Core\DBM-Core.lua:5221
 PLAYER_REGEN_DISABLED = <function> defined @DBM-Core\DBM-Core.lua:5460
 FireEvent = <function> defined @DBM-Core\DBM-Core.lua:1676
 CreateModLocalization = <function> defined @DBM-Core\DBM-Core.lua:12545
 SCENARIO_COMPLETED = <function> defined @DBM-Core\DBM-Core.lua:4084
 IsEnabled = <function> defined @DBM-Core\DBM-Core.lua:7180
 GetMyPlayerInfo = <function> defined @DBM-Core\DBM-Core.lua:3235
 Capitalize = <function> defined @DBM-Core\DBM-Core.lua:7290
 ADDON_LOADED = <function> defined @DBM-Core\DBM-Core.lua:1372
 IconNumToTexture = <function> defined @DBM-Core\DBM-Core.lua:7356
 BattleMusic = <table> {
 }
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @DBM-Core\DBM

**Comment by MysticalOS** [comment]
That's unrelated issue and fixed in latest alpha of spelltimers, just not tagged yet

**Comment by QartemisT** [comment]
Closing, as this was fixed ages ago.
